/*
 * File: app/view/Introduction.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FindAHospital.view.Login', {
    extend: 'Ext.Container',
    alias: 'widget.login',
    requires: ['Ext.Map', 'Ext.util.DelayedTask', 'Ext.Img', 'Ext.form.Panel', 'Ext.form.FieldSet', 'Ext.field.Email', 'Ext.field.Password', 'Ext.field.Checkbox', 'Ext.Label'],
    config: {
        layout: {
                    type: 'vbox',
                    align: 'center'
                },
        scrollable:'vertical',
        style: 'background-color:#FFFFFF;',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top'
            },
             {
                xtype: 'spacer'
            },
            {
                xtype: 'label',
                html: 'Login failed!',
                itemId: 'signInFailedLabel',
                hidden: true,
                hideAnimation: 'fadeOut',
                showAnimation: 'fadeIn',
                style: 'color:#990000;margin:5px 0px;'
            },

            {
                xtype: 'fieldset',
                title: 'Login Details',
                items: [
                    {
                          xtype: 'textfield',
                          name: 'username',
                          id: 'userNameTextField',
                          required: true,
                          placeHolder: 'enter username'
                    },
                    {
                          xtype: 'passwordfield',
                          name: 'password',
                          id: 'passwordTextField',
                          required: true,
                          placeHolder: 'enter password'
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'action',
                id: 'logInButton',
                text: 'Log In',
                padding: '10px'
            },
            {
                xtype: 'image',
                src: 'resources/images/hospital-login-page.jpeg',
                style: Ext.Viewport.getOrientation() == 'portrait' ? 'width:700px;height:700px;margin:auto;padding: 10 10 10 10;' : 'width:350px;height:450px;margin:auto;padding: 10 10 10 10;'
            }
        ],
        listeners: [{
            delegate: '#logInButton',
            event: 'tap',
            fn: 'onLogInButtonTap'
        }]
    },
    
    onLogInButtonTap: function () {
        var me = this;

        var usernameField = me.down('#userNameTextField'),
            passwordField = me.down('#passwordTextField'),
            label = me.down('#signInFailedLabel');

        label.hide();

        var username = usernameField.getValue(),
            password = passwordField.getValue();

        // Using a delayed task in order to give the hide animation above
        // time to finish before executing the next steps.
        var task = Ext.create('Ext.util.DelayedTask', function () {

            label.setHtml('');

            me.fireEvent('signInCommand', me, username, password);

            usernameField.setValue('');
            passwordField.setValue('');
        });

        task.delay(500);
    }

});