/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FindAHospital.controller.HospitalList', {
    extend: 'Ext.app.Controller',
    requires: [
            'FindAHospital.view.HospitalListContainer',
            'FindAHospital.view.HospitalSearch',
            'FindAHospital.view.HospitalList',
            'FindAHospital.view.MapWithSearchDetail',
            'FindAHospital.store.Locations',
            'FindAHospital.model.Location'
    ],
    config: {
        refs: {
            hospitalList: {
                        selector: 'hospitallist',
                        xtype: 'hospitallist',
                        autoCreate: true
                    },
            mapWithSearchDetail: {
                        selector: 'mapwithsearchdetail',
                        xtype: 'mapwithsearchdetail',
                        autoCreate: true
            }
        },
        control: {
            "hospitallist": {
                itemtap: 'onHospitalListItemTap'
            }
        }
    },

    getSlideLeftTransition: function () {
        return { type: 'slide', direction: 'left' };
    },

    onHospitalListItemTap: function(list, index, node, record) {
        // var editButton = this.getEditButton()

        if (!this.mapWithSearchDetail) {
            this.mapWithSearchDetail = Ext.create('FindAHospital.view.MapWithSearchDetail');
        }

        // Bind the record onto the show contact view
        this.mapWithSearchDetail.setRecord(record);
        // Push the show contact view into the navigation view
        Ext.Viewport.animateActiveItem(this.getMapWithSearchDetail(), this.getSlideLeftTransition());
    }

});


